{% set name = "xarray-spatial" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f51fde07687205e6d2497295e71d65a856f90c3acae93d9bc36363ec82d739ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - dask-core
    - datashader
    - numba
    - numpy
    - pandas
    - pillow
    - requests
    - scipy
    - xarray

test:
  imports:
    - xrspatial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
