{% set name = "xarray-spatial" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 581202183173dd97f3cc8acf8772f4125dd9c9b3a994e74c6946e2d438374597

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xrspatial = xrspatial.__main__:main

requirements:
  host:
    - python >=3.6
    - pyct-core
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - dask-core
    - datashader
    - numba
    - numpy >=1.7,<=1.20
    - pandas
    - pillow
    - pyct-core <=0.4.6
    - requests
    - scipy
    - spatialpandas
    - xarray

test:
  imports:
    - xrspatial
  commands:
    - pip check
    - xrspatial --help
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - brendancol
    - giancastro
    - ocefpaf
