{% set name = "xarray-spatial" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44465d7e953403afbdb877727c295ce9f566e554781330f5a2065e3b3b6319bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xrspatial = xrspatial.__main__:main

requirements:
  host:
    - python >=3.6
    - pyct-core
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - dask-core
    - datashader
    - numba
    - numpy
    - pandas
    - pillow
    - pyct-core <=0.4.6
    - requests
    - scipy
    - spatialpandas
    - xarray

test:
  imports:
    - xrspatial
  commands:
    - pip check
    - xrspatial --help
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
