{% set name = "xarray-spatial" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cb6fd112138fe3430186429179887e1e8dcb5c5c9025c506d0514a805f93ad0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - dask
    - datashader
    - numba
    - numpy
    - pandas
    - pillow
    - requests
    - scikit-learn
    - scipy
    - xarray

test:
  imports:
    - xrspatial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xarray-spatial/
  summary: xarray-based spatial analysis tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
